# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171011_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actication_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
